suffix = ".tif";
// multiple input folders
inputDirs = newArray();
addMore = true;
while (addMore) {
    dir = getDirectory("Choose an Input Directory");
    inputDirs = Array.concat(inputDirs, dir);
    addMore = getBoolean("Add another input folder?");
}
run("Set Measurements...", "area mean redirect=None decimal=3");
for (d=0; d<inputDirs.length; d++) {
    processFolder(inputDirs[d]);
}
// output folder
output = getDirectory("Output Directory");
selectWindow("Summary");
Table.save(output + "combined_summary.csv");
// clear everything
run("Clear Results");
selectWindow("Summary");
run("Close");

function processFolder(input) {
	list = getFileList(input);
	for (i=0; i<list.length; i++) {
	    if(File.isDirectory(list[i]))
			processFolder(""+input+list[i]);
	    if(endsWith(list[i],suffix))
			processFile(input,list[i]);
	}
}

function processFile(input, file) {
run("Bio-Formats Importer", "open=[" + input + file + "] autoscale color_mode=Default view=Hyperstack stack_order=XYCZT");
run("RGB Color");
a = getTitle();

// ================= TISSUE ROI + CLEAR BACKGROUND =================
// Reset ROI Manager so ROIs don't accumulate across images
roiManager("reset");

// Duplicate the image to build the tissue mask, so the original is untouched
run("Duplicate...", "title=tissue_mask");
run("8-bit");
setThreshold(11, 255);
run("Convert to Mask");
run("Fill Holes");
run("Create Selection");
roiManager("Add");
close(); // closes "tissue_mask"

// Apply the tissue ROI to the original image and clear everything outside it
selectWindow(a);
roiManager("Select", 0);
run("Clear Outside");
run("Select None");
// ====================================================================

// Color Thresholder 2.18.0/1.54p
// Autogenerated macro, single images only!
min=newArray(3);
max=newArray(3);
filter=newArray(3);
a=getTitle();
run("HSB Stack");
run("Convert Stack to Images");
selectWindow("Hue");
rename("0");
selectWindow("Saturation");
rename("1");
selectWindow("Brightness");
rename("2");
min[0]=20;
max[0]=237;
filter[0]="stop";
min[1]=159;
max[1]=255;
filter[1]="pass";
min[2]=141;
max[2]=255;
filter[2]="pass";
for (j=0;j<3;j++){
  selectWindow(""+j);
  setThreshold(min[j], max[j]);
  run("Convert to Mask");
  if (filter[j]=="stop")  run("Invert");
}
imageCalculator("AND create", "0","1");
imageCalculator("AND create", "Result of 0","2");
for (j=0;j<3;j++){
  selectWindow(""+j);
  close();
}
selectWindow("Result of 0");
close();
selectWindow("Result of Result of 0");
rename(a);
roiManager("Select", 0);
run("Analyze Particles...", "size=35-Infinity display summarize limit");
run("Select None");
run("Close All");
}